version: '2'
services:
    budget-app:
        image: budget
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:sqlserver://budget-mssql:1433;database=jhitest
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    budget-mssql:
        extends:
            file: mssql.yml
            service: budget-mssql
